language: ruby
rvm:
- 1.9.3
services:
- mongodb
script: rspec spec
before_install:
- openssl aes-256-cbc -K $encrypted_b130abd58c43_key -iv $encrypted_b130abd58c43_iv
  -in config.yml.enc -out spec/config.yml -d
